#!/bin/bash 
#
# Simple powerfull bash template engine (aka macgyver-style smarty) 
#
 
fetch(){
  IFS=''; cat - | sed 's/\\/\\\\\\\\/g' | while read line; do 
    line="$(eval "echo \"$( echo "$line" | sed 's/"/\\"/g')\"")"; # process bash in snippet
    echo "$line"
  done
}

tohtml(){
  cat - > /tmp/.bashdown
  curl -s -X POST -H "Content-Type: text/x-markdown" --data-binary @/tmp/.bashdown https://api.github.com/markdown/raw
}

# fetch and htmlize using github, or fetch only 
if [[ "$1" == "--html" ]]; then 
  cat - | fetch | tohtml; 
else 
  cat - | fetch; 
fi
